import jsPDF from 'jspdf';
import { AnalysisResult } from './fire-safety/calculator';

export function generatePDFReport(result: AnalysisResult) {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();

    // Title
    doc.setFontSize(22);
    doc.setTextColor(41, 128, 185); // Blue
    doc.text('Fire Safety Signage Requirements', 20, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated on: ${date}`, 20, 28);
    doc.text('Compliance Standard: NBC India', 20, 33);

    // Summary
    doc.setDrawColor(200);
    doc.line(20, 40, 190, 40);

    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text('Executive Summary', 20, 50);

    doc.setFontSize(11);
    doc.text(`Total Rooms Detected: ${result.rooms}`, 20, 60);
    doc.text(`Total Exits Found: ${result.exits}`, 20, 67);
    doc.text(`Total Signage Required: ${result.signageRequired}`, 20, 74);

    // Requirements Table
    let y = 90;
    doc.setFontSize(14);
    doc.text('Detailed Requirements', 20, y);
    y += 10;

    // Header
    doc.setFillColor(240, 240, 240);
    doc.rect(20, y - 6, 170, 8, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('Signage Type', 25, y);
    doc.text('Qty', 100, y);
    doc.text('Regulation', 120, y);
    y += 10;

    // Rows
    doc.setFont('helvetica', 'normal');
    result.requirements.forEach((req) => {
        doc.text(req.type, 25, y);
        doc.text(req.count.toString(), 100, y);
        doc.text(req.regulation, 120, y);

        // Reason text (wrapped)
        doc.setFontSize(9);
        doc.setTextColor(100);
        const splitReason = doc.splitTextToSize(req.reason, 160);
        doc.text(splitReason, 25, y + 5);
        doc.setTextColor(0);
        doc.setFontSize(10);

        y += 10 + (splitReason.length * 4);

        // Dotted line
        doc.setDrawColor(220);
        doc.setLineDash([1, 1], 0);
        doc.line(20, y - 3, 190, y - 3);
        doc.setLineDash([], 0);
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by Signage Analyzer AI', 100, 280, { align: 'center' });

    // Download
    doc.save('fire-safety-report.pdf');
}
